{ userName, modulesPath, ... }:
# Generated by nixos-infect
{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
  boot.loader.grub.device = "/dev/vda";
  boot.initrd.kernelModules = [ "nvme" ];
  fileSystems."/" = { device = "/dev/vda2"; fsType = "ext4"; };

  boot.cleanTmpDir = true;
  zramSwap.enable = true;
  networking.hostName = "bennett-server";

  services.fail2ban.enable = true;
  jails.DEFAULT = ''
    bantime = 3600
  '';

  jails.sshd = ''
      filter = sshd
      maxretry = 4
      action   = iptables[name=ssh, port=ssh, protocol=tcp]
      enabled  = true
    '';

  sops.secrets.defaultSopsFile = ./secrets.yaml;
  sops.secrets."nextcloud/admin_pw" = {}
  sops.secrets."nextcloud/db_pw" = {}
}
